# PyTorch 基础 : 张量

In [1]:
import torch
import numpy as np
torch.__version__

'1.4.0+cpu'

## 张量(Tensor)
张量的英文是Tensor，它是PyTorch里面基础的运算单位，与Numpy的ndarray相同都表示的是一个多维的矩阵。  
与ndarray的最大区别就是，PyTorch的Tensor可以在 GPU 上运行，而 numpy 的 ndarray 只能在 CPU 上运行，在GPU上运行大大加快了运算速度。

生成一个简单的张量

In [3]:
x = torch.rand(2,3) #可以任意生成想要的size
x

tensor([[0.0935, 0.6569, 0.5103],
        [0.9278, 0.3666, 0.4313]])

In [4]:
# 可以使用与numpy相同的shape属性查看
print(x.shape)
# 也可以使用size()函数，返回的结果都是相同的
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


张量（Tensor）是一个定义在一些向量空间和一些对偶空间的笛卡儿积上的多重线性映射，**其坐标是|n|维空间内，有|n|个分量的一种量**， 其中每个分量都是坐标的函数， 而在坐标变换时，这些分量也依照某些规则作线性变换。r称为该张量的秩或阶（与矩阵的秩和阶均无关系）。 (来自百度百科)

下面生成一些多维的张量：

In [6]:
y = torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.1626, 0.5217, 0.0805, 0.2814, 0.7096],
          [0.8300, 0.0504, 0.8794, 0.9927, 0.5588],
          [0.3114, 0.5773, 0.9506, 0.6100, 0.8543],
          [0.9103, 0.2707, 0.3997, 0.8809, 0.0833]],

         [[0.8352, 0.8999, 0.6061, 0.0061, 0.4762],
          [0.6019, 0.4470, 0.8264, 0.3501, 0.5152],
          [0.2360, 0.4659, 0.2075, 0.1191, 0.4223],
          [0.7055, 0.4247, 0.3709, 0.4218, 0.4504]],

         [[0.4395, 0.0863, 0.2670, 0.1420, 0.8760],
          [0.1799, 0.2767, 0.5948, 0.4587, 0.9363],
          [0.8468, 0.3359, 0.1154, 0.5371, 0.6918],
          [0.7947, 0.8429, 0.3607, 0.4986, 0.1863]]],


        [[[0.8445, 0.7919, 0.0580, 0.9765, 0.4516],
          [0.1577, 0.7196, 0.4658, 0.6533, 0.2205],
          [0.4177, 0.8710, 0.3940, 0.3759, 0.6550],
          [0.7965, 0.0646, 0.8755, 0.3184, 0.4420]],

         [[0.2400, 0.8456, 0.6111, 0.6109, 0.7386],
          [0.8892, 0.6695, 0.2279, 0.9076, 0.2414],
          [0.0120, 0.8450, 0.8968, 0.8159, 0.8134],
  

在同构的意义下:
* 第零阶张量 （r = 0） 为标量 （Scalar）
* 第一阶张量 （r = 1） 为向量 （Vector)
* 第二阶张量 （r = 2） 则成为矩阵 （Matrix)
* 第三阶以上的统称为多维张量。

其中要特别注意的就是标量，我们先生成一个标量：

In [7]:
scalar = torch.tensor(2.333332)
print(scalar)
scalar.size()

tensor(2.3333)


torch.Size([])

对于标量，我们可以直接使用 .item() 从中取出其对应的python对象的数值

In [8]:
scalar.item()

2.333332061767578

特别的：如果张量中只有一个元素的tensor也可以调用`tensor.item`方法

In [9]:
tensor = torch.tensor([3.1433223]) 
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [11]:
tensor.item()

3.143322229385376

### 基本类型
Tensor的基本数据类型有五种：
- 32位浮点型：torch.FloatTensor。 (默认)
- 64位整型：torch.LongTensor。
- 32位整型：torch.IntTensor。
- 16位整型：torch.ShortTensor。
- 64位浮点型：torch.DoubleTensor。

除以上数字类型外，还有
byte和chart型